# Generated by Django 2.0.5 on 2018-08-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='likes_counter',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='likes counter'),
        ),
    ]
