# Generated by Django 2.0.5 on 2018-08-21 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-date',), 'verbose_name': 'News item', 'verbose_name_plural': 'News items'},
        ),
    ]
