# Generated by Django 2.0.5 on 2018-09-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tag'),
        ('news', '0002_news_likes_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='news', to='main.Tag', verbose_name='tags'),
        ),
    ]
