# Generated by Django 2.0.5 on 2018-10-23 15:09

import core.models.base_model
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=core.models.base_model.BaseModel.obfuscated_upload, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='news',
            name='preview',
            field=models.TextField(blank=True, help_text='Preview is displayed on index page', null=True, verbose_name='preview'),
        ),
        migrations.AddField(
            model_name='news',
            name='tab_title',
            field=models.CharField(help_text='Tab title is displayed on index page', max_length=48, null=True, verbose_name='tab title'),
        ),
    ]
