# Generated by Django 2.0.5 on 2018-10-23 19:09

from django.db import migrations, models
import libs.autoslug.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20181023_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=libs.autoslug.fields.AutoSlugField(default='', editable=False, populate_from='title', unique_with=('title',), verbose_name='Slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='title'),
        ),
    ]
