# -*- coding: utf-8 -*-
# Generated by Denis on 2046-08-15 10:15
from __future__ import unicode_literals

from django.db import migrations
from ..models import DiaryEntry


def add_tags(apps, schema_editor):
    """Add tags for all exisiting diary entries."""
    for entry in DiaryEntry.objects.all():
        entry.populate_tags()


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_auto_20181106_1838'),
    ]

    operations = [
        migrations.RunPython(
            add_tags,
            migrations.RunPython.noop
        ),
    ]
