# Generated by Django 2.1.2 on 2019-02-22 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def migrate_tags(apps, schema_editor):
    User = apps.get_model('users', 'User')
    DiaryTag = apps.get_model('diary', 'DiaryTag')
    DiaryTagValue = apps.get_model('diary', 'DiaryTagValue')

    root = User.objects.filter(is_superuser=True).first()

    if root:
        print('  Root was found. Migrating tags...')
        DiaryTag.objects.all().update(author=root)
        DiaryTagValue.objects.all().update(author=root)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diary', '0005_data_migration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diarytag',
            options={'ordering': ('name',), 'verbose_name': 'Diary tag', 'verbose_name_plural': 'Diary tags'},
        ),
        migrations.AddField(
            model_name='diarytag',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diary_tags', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='diarytagvalue',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diary_tag_values', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.RunPython(
            migrate_tags,
            migrations.RunPython.noop
        ),
    ]
