# Generated by Django 3.1 on 2020-12-27 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diary', '0007_auto_20200920_1007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diarytag',
            options={'ordering': ('group', 'name'), 'verbose_name': 'Diary tag', 'verbose_name_plural': 'Diary tags'},
        ),
        migrations.CreateModel(
            name='DiaryTagGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('color', models.CharField(blank=True, max_length=32, null=True, verbose_name='Color')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='Order')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diary_tag_groups', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Diary tag group',
                'verbose_name_plural': 'Diary tag groups',
                'ordering': ('order',),
            },
        ),
        migrations.AddField(
            model_name='diarytag',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='diary.diarytaggroup', verbose_name='Group'),
        ),
    ]
