# Generated by Django 2.0.5 on 2018-06-01 11:00

import adminsortable.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='artist',
            field=adminsortable.fields.SortableForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='music.Artist', verbose_name='Artist'),
        ),
    ]
