# Generated by Django 3.1 on 2020-09-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20191026_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='slug',
            field=models.CharField(db_index=True, max_length=64, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='track',
            name='slug',
            field=models.CharField(db_index=True, max_length=64, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
