# Generated by Django 2.0.5 on 2018-08-23 15:20

import core.models.base_model
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import libs.autoslug.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0002_videofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtitle')),
                ('slug', libs.autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique_with=('title',), verbose_name='Slug')),
                ('description', models.TextField(blank=True, help_text='Short description of blog entry', null=True, verbose_name='Description')),
                ('wide_image', models.ImageField(help_text='Image for index page', null=True, upload_to=core.models.base_model.BaseModel.obfuscated_upload, verbose_name='Wide image')),
                ('text', models.TextField(blank=True, help_text='Main blog text', null=True, verbose_name='Text')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('show_gallery', models.BooleanField(default=False, verbose_name='show_gallery')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_enties', to='files.VideoFile', verbose_name='Video')),
            ],
            options={
                'verbose_name': 'Blog entry',
                'verbose_name_plural': 'Blog entries',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('image', models.ImageField(null=True, upload_to=core.models.base_model.BaseModel.obfuscated_upload, verbose_name='image')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='description')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='Order')),
                ('blog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.BlogEntry', verbose_name='blog')),
            ],
            options={
                'verbose_name': 'BlogImage',
                'verbose_name_plural': 'BlogImages',
                'ordering': ('order',),
            },
        ),
    ]
