# Generated by Django 2.0.5 on 2018-08-20 13:38

import core.models.base_model
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0002_videofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Short description of blog entry', null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.base_model.BaseModel.obfuscated_upload, verbose_name='Image')),
                ('text', models.TextField(blank=True, help_text='Main blog text', null=True, verbose_name='Text')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_enties', to='files.VideoFile', verbose_name='Video')),
            ],
            options={
                'verbose_name': 'Blog entry',
                'verbose_name_plural': 'Blog entries',
                'ordering': ('created',),
            },
        ),
    ]
