# Generated by Django 2.0.5 on 2018-08-20 14:50

from django.db import migrations
import libs.autoslug.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogentry',
            name='slug',
            field=libs.autoslug.fields.AutoSlugField(default=1, editable=False, populate_from='title', unique_with=('title',), verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
