# Generated by Django 2.0.5 on 2018-08-24 14:17

import core.models.base_model
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Blog relation',
                'verbose_name_plural': 'Blog relations',
                'ordering': ('order',),
            },
        ),
        migrations.AlterField(
            model_name='blogentry',
            name='wide_image',
            field=models.ImageField(blank=True, help_text='Image for index page', null=True, upload_to=core.models.base_model.BaseModel.obfuscated_upload, verbose_name='Wide image'),
        ),
        migrations.AddField(
            model_name='blogrelation',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='blog.BlogEntry', verbose_name='Blog'),
        ),
        migrations.AddField(
            model_name='blogrelation',
            name='related_blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relations_2', to='blog.BlogEntry', verbose_name='Related blog'),
        ),
    ]
