# Generated by Django 2.0.5 on 2018-08-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogentry_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogentry',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtitle'),
        ),
    ]
