# Generated by Django 2.0.5 on 2018-08-28 17:07

from django.db import migrations

import imagekit.models.fields

import core.models.base_model


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogentry_likes_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimage',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to=core.models.base_model.BaseModel.obfuscated_upload, verbose_name='Image'),
        ),
    ]
