# Generated by Django 2.0.5 on 2018-09-03 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogentry_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogimage',
            options={'ordering': ('order',), 'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='blogrelation',
            options={'ordering': ('order',), 'verbose_name': 'Relation', 'verbose_name_plural': 'Relations'},
        ),
        migrations.AddField(
            model_name='blogentry',
            name='next_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blog.BlogEntry', verbose_name='Next part'),
        ),
        migrations.AddField(
            model_name='blogentry',
            name='prev_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blog.BlogEntry', verbose_name='Previous part'),
        ),
        migrations.AlterField(
            model_name='blogentry',
            name='date',
            field=models.DateTimeField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='blogentry',
            name='show_gallery',
            field=models.BooleanField(default=False, verbose_name='Show gallery'),
        ),
    ]
