# Generated by Django 2.1.5 on 2019-07-30 15:15

import core.models.base_model
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180903_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Blog series',
                'verbose_name_plural': 'Blog series',
            },
        ),
        migrations.CreateModel(
            name='BlogSeriesItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='Order')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Custom title')),
            ],
            options={
                'verbose_name': 'Blog entry',
                'verbose_name_plural': 'Blog entries',
                'ordering': ('order',),
            },
        ),
        migrations.RemoveField(
            model_name='blogrelation',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='blogrelation',
            name='related_blog',
        ),
        migrations.RemoveField(
            model_name='blogentry',
            name='next_part',
        ),
        migrations.RemoveField(
            model_name='blogentry',
            name='prev_part',
        ),
        migrations.RemoveField(
            model_name='blogentry',
            name='wide_image',
        ),
        migrations.AddField(
            model_name='blogentry',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=core.models.base_model.BaseModel.obfuscated_upload, verbose_name='Image'),
        ),
        migrations.DeleteModel(
            name='BlogRelation',
        ),
        migrations.AddField(
            model_name='blogseriesitem',
            name='entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series_item', to='blog.BlogEntry', verbose_name='blog'),
        ),
        migrations.AddField(
            model_name='blogseriesitem',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='blog.BlogSeries', verbose_name='Series'),
        ),
    ]
