# Generated by Django 3.1 on 2020-09-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190730_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='slug',
            field=models.CharField(db_index=True, max_length=64, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
