# Generated by Django 2.0.5 on 2018-05-13 18:08

import django.db.models.deletion
from django.db import migrations, models

import django_extensions.db.fields

import core.models.base_model


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('data', models.FileField(null=True, upload_to=core.models.base_model.BaseModel.default_upload, verbose_name='Data')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
            },
        ),
        migrations.CreateModel(
            name='FileCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=64, null=True, verbose_name='Name')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'File category',
                'verbose_name_plural': 'File categories',
                'ordering': ('order',),
            },
        ),
        migrations.AddField(
            model_name='file',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='files.FileCategory', verbose_name='Category'),
        ),
    ]
