# Generated by Django 2.0.5 on 2018-09-03 10:07

from django.db import migrations, models

import core.models.base_model


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20180824_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videofile',
            name='data',
        ),
        migrations.RemoveField(
            model_name='videofile',
            name='link',
        ),
        migrations.RemoveField(
            model_name='videofile',
            name='link_hd',
        ),
        migrations.RemoveField(
            model_name='videofile',
            name='link_low',
        ),
        migrations.AddField(
            model_name='videofile',
            name='data_1080',
            field=models.FileField(blank=True, null=True, upload_to=core.models.base_model.BaseModel.default_upload, verbose_name='File (1080p)'),
        ),
        migrations.AddField(
            model_name='videofile',
            name='data_720',
            field=models.FileField(blank=True, null=True, upload_to=core.models.base_model.BaseModel.default_upload, verbose_name='File (720p)'),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='source',
            field=models.CharField(choices=[('file', 'File'), ('youtube', 'Youtube')], default='file', max_length=64, null=True, verbose_name='Source'),
        ),
    ]
