# Generated by Django 2.0.5 on 2018-09-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_auto_20180903_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofile',
            name='source_original',
            field=models.TextField(blank=True, null=True, verbose_name='Source uncompressed 100500p'),
        ),
    ]
