# Generated by Django 2.0.5 on 2018-10-15 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_videofile_source_original'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ('name',), 'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
    ]
