# Generated by Django 2.0.5 on 2018-08-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180824_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogentry',
            name='likes_counter',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='likes counter'),
        ),
    ]
