# Generated by Django 2.0.5 on 2018-09-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180828_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogentry',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
    ]
