# Generated by Django 2.0.5 on 2018-08-23 22:27

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RedirectPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('source', models.CharField(db_index=True, max_length=255, null=True, unique=True, verbose_name='Source')),
                ('destination', models.CharField(max_length=255, null=True, verbose_name='Destination')),
            ],
            options={
                'verbose_name': 'Redirect page',
                'verbose_name_plural': 'Redirect pages',
            },
        ),
    ]
