# Generated by Django 2.0.5 on 2018-09-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirectpage',
            name='destination',
            field=models.CharField(max_length=255, null=True, verbose_name='Full path'),
        ),
        migrations.AlterField(
            model_name='redirectpage',
            name='source',
            field=models.CharField(db_index=True, max_length=255, null=True, unique=True, verbose_name='Short URL'),
        ),
    ]
