# Generated by Django 2.0.5 on 2018-09-27 11:11

from django.db import migrations, models
import django_extensions.db.fields
import libs.autoslug.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180911_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255, null=True, unique=True, verbose_name='Name')),
                ('slug', libs.autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique_with=('name',), verbose_name='Slug')),
                ('color', models.CharField(help_text='Text color: #FFF', max_length=255, null=True, verbose_name='color')),
                ('background', models.CharField(help_text='Background color: #FFF', max_length=255, null=True, verbose_name='background')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ('name',),
            },
        ),
    ]
