# Generated by Django 2.0.5 on 2018-09-10 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_track_likes_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='image_thumbnail',
        ),
    ]
