# Generated by Django 2.0.5 on 2018-10-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_remove_track_image_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='color',
            field=models.CharField(blank=True, help_text='Accent color for index page', max_length=255, null=True, verbose_name='color'),
        ),
        migrations.AddField(
            model_name='track',
            name='lead',
            field=models.TextField(blank=True, help_text='Displayed before full description', null=True, verbose_name='Lead description'),
        ),
    ]
