# Generated by Django 3.2.11 on 2022-02-01 14:24

import django.db.models.deletion
from django.db import migrations, models

import adminsortable.fields
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_videofile_duration'),
        ('music', '0007_auto_20200920_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicVideoType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('slug', models.CharField(db_index=True, max_length=64, null=True, unique=True, verbose_name='Slug')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Music video type',
                'verbose_name_plural': 'Music video types',
                'ordering': ('order',),
            },
        ),
        migrations.AddField(
            model_name='album',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.CreateModel(
            name='AlbumFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('button_text', models.CharField(max_length=255, null=True, verbose_name='Button text')),
                ('button_class', models.CharField(blank=True, max_length=255, verbose_name='Button class')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='Order')),
                ('album', adminsortable.fields.SortableForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_files', to='music.album', verbose_name='Album')),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_files', to='files.file', verbose_name='File')),
            ],
            options={
                'verbose_name': 'Album file',
                'verbose_name_plural': 'Album files',
                'ordering': ('order',),
            },
        ),
        migrations.AddField(
            model_name='musicvideo',
            name='video_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='music.musicvideotype', verbose_name='Type'),
        ),
    ]
