# Generated by Django 2.0.5 on 2018-09-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_auto_20180903_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videofile',
            name='data_1080',
        ),
        migrations.RemoveField(
            model_name='videofile',
            name='data_720',
        ),
        migrations.AddField(
            model_name='videofile',
            name='source_1080',
            field=models.TextField(blank=True, null=True, verbose_name='Source 1080p'),
        ),
        migrations.AddField(
            model_name='videofile',
            name='source_360',
            field=models.TextField(blank=True, null=True, verbose_name='Source 360p'),
        ),
        migrations.AddField(
            model_name='videofile',
            name='source_480',
            field=models.TextField(blank=True, null=True, verbose_name='Source 480p'),
        ),
        migrations.AddField(
            model_name='videofile',
            name='source_720',
            field=models.TextField(blank=True, null=True, verbose_name='Source 720p'),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='source',
            field=models.CharField(choices=[('src', 'Source'), ('youtube', 'Youtube')], default='src', max_length=64, null=True, verbose_name='Source'),
        ),
    ]
