# Generated by Django 2.0.5 on 2018-08-21 12:34

import core.models.base_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_auto_20180820_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofile',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.base_model.BaseModel.obfuscated_upload, verbose_name='Poster image'),
        ),
    ]
