# -*- coding: utf-8 -*-
# Generated by Denis on 2046-08-15 10:15
from __future__ import unicode_literals

from django.db import migrations


def set_done(apps, schema_editor):
    DiaryEntry = apps.get_model('diary', 'DiaryEntry')
    DiaryEntry.objects.exclude(text="").update(done=True)


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_auto_20181015_1827'),
    ]

    operations = [
        migrations.RunPython(
            set_done,
            migrations.RunPython.noop
        ),
    ]
