# Generated by Django 3.1 on 2020-09-20 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_videofile_duration'),
        ('diary', '0006_auto_20190222_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Done'),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='diary_entries', to='files.File', verbose_name='Files'),
        ),
        migrations.AlterField(
            model_name='diarytag',
            name='entries',
            field=models.ManyToManyField(blank=True, through='diary.DiaryTagValue', to='diary.DiaryEntry', verbose_name='Entries'),
        ),
        migrations.AlterField(
            model_name='diarytag',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='diarytagvalue',
            name='entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='diary.diaryentry', verbose_name='Entry'),
        ),
        migrations.AlterField(
            model_name='diarytagvalue',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='values', to='diary.diarytag', verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='diarytagvalue',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Value'),
        ),
    ]
